<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Guestbook\Module'                        => __DIR__ . '/Module.php',
    'Guestbook\Controller\IndexController' => __DIR__ . '/src/Guestbook/Controller/IndexController.php',
    'GuestbookTest\Framework\TestCase'        => __DIR__ . '/tests/Guestbook/Framework/TestCase.php',
    'GuestbookTest\SampleTest'                => __DIR__ . '/tests/Guestbook/SampleTest.php',
);
