        <?= $this->partial('menu.phtml') ?>
    
        <div id="header-wrapper">
        	<div id="header">
        		<div id="logo">
        			<h1><a href="#"><?= $this->headTitle()->renderTitle() ?></a></h1>
        			<p>ZF2 ESGi training</p>
        		</div>
        	</div>
        </div>
        
    	<div id="banner">
    		<img src="img/guest-book.jpg" width="1000" height="300" alt="" />
    	</div>