<?= $this->doctype() ?>

<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License
-->
<html  xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
<?= $this->headTitle($this->translate('Guestbook'))
    ->append($this->translate('ZF2 Tutorial'))
    ->setSeparator(' - ')
    ->setIndent(8) ?>

        <!-- Les métas -->
<?= $this->headMeta()
    ->appendName('keywords', 'ESGi, Zend Framework 2, Training, ZF2, GS Consulting')
    ->appendName('description', 'Tutorial')
    ->appendHttpEquiv('content-type', "text/html; charset=utf-8")
    ->setIndent(8) ?>

        <!-- Les styles -->
<?php echo $this->headLink([
        'rel'  => 'shortcut icon', 
        'type' => 'image/vnd.microsoft.icon', 
        'href' => $this->basePath() . '/img/favicon.ico'])
    ->appendStylesheet('http://fonts.googleapis.com/css?family=Arvo')
    ->appendStylesheet('http://fonts.googleapis.com/css?family=Coda:400,800')
    ->appendStylesheet($this->basePath('css/style.css'))
    ->setIndent(8) ?>

    </head>
    
    <body>
    
    	<?= $this->partial ('header.phtml') ?>
	
    	<div id="wrapper">
        	<div id="page">
                <div id="page-bgtop">
                    <div id="page-bgbtm">
                    
                        <?= $this->content ?>
        				
                        <?= $this->partial('sidebar.phtml') ?>

                        <div style="clear: both;">&nbsp;</div>
                    </div>
        		</div>
        	</div>
        	<!-- end #page -->
    	</div>
    	
    	<?= $this->partial('footer.phtml') ?>
	</body>
</html>
