<?php echo $this->doctype(); ?>
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License
-->
<html  xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
<?php echo $this->headTitle($this->translate('Guestbook'))
    ->append($this->translate('ZF2 Tutorial'))
    ->setSeparator(' - ')
    ->setIndent(8)?>

        <!-- Les métas -->
<?php echo $this->headMeta()
    ->appendName('keywords', 'ESGi, Zend Framework 2, Training, ZF2, GS Consulting')
    ->appendName('description', 'Tutorial')
    ->appendHttpEquiv('content-type', "text/html; charset=utf-8")
    ->setIndent(8) ?>

        <!-- Les styles -->
<?php echo $this->headLink([
        'rel'  => 'shortcut icon', 
        'type' => 'image/vnd.microsoft.icon', 
        'href' => $this->basePath() . '/img/favicon.ico'])
    ->appendStylesheet('http://fonts.googleapis.com/css?family=Arvo')
    ->appendStylesheet('http://fonts.googleapis.com/css?family=Coda:400,800')
    ->appendStylesheet($this->basePath('css/style.css'))
    ->setIndent(8) ?>

    </head>
    
    <body>
    
        <div id="menu-wrapper">
        	<div id="menu">
        		<ul>
        			<li class="current_page_item"><a href="#">Homepage</a></li>
        			<li><a href="#">Content</a></li>
        			<li><a href="guestbook">Guestbook</a></li>
        		</ul>
        	</div>
        	<!-- end #menu -->
        </div>
    
        <div id="header-wrapper">
        	<div id="header">
        		<div id="logo">
        			<h1><a href="#"><?= $this->headTitle()->renderTitle() ?></a></h1>
        			<p>ZF2 ESGi training</p>
        		</div>
        	</div>
        </div>
        
    	<div id="banner">
    		<img src="img/guest-book.jpg" width="1000" height="300" alt="" />
    	</div>
	
    	<div id="wrapper">
        	<div id="page">
                <div id="page-bgtop">
                    <div id="page-bgbtm">
                    
                        <?= $this->content ?>
        				
                        <?= $this->partial('sidebar.phtml') ?>

                        <div style="clear: both;">&nbsp;</div>
                    </div>
        		</div>
        	</div>
        	<!-- end #page -->
    	</div>
    	
    	<?= $this->partial('footer.phtml') ?>
	</body>
</html>
